### ISSUE TITLE
KOI8-R encoding

### ISSUE THREAD

**Issue by vazhnov** [eddyem/lectures#2]
Hello!

Using koi8r encoding in 2022 looks a little bit weird… is it on purpose, or by historical reasons?

**Comment by eddyem** [comment]
Do you offer to use CP1251? In Linux? Seriously?

**Comment by vazhnov** [comment]
@eddyem, no, of course not CP1251. I'm suggesting to use UTF-8.

**Comment by eddyem** [comment]
The place of this piece of shit is only in X-applications. Not in console or text files!!!

**Comment by vazhnov** [comment]
Ok, so a 8-bit encoding was chosen on purpose.
Got it!
Thanks!
